#! /bin/sh

if [ -z $1 ]
then
    echo "must specify postgres database"
    exit 1
fi

DBSNAP_HOME=/opt/dbsnap
SHORT_COMMIT=`git rev-parse --short HEAD`
COMMIT=`git rev-parse HEAD`
DB=$1
DUMP_LOC=$DBSNAP_HOME/$DB
DUMP_NAME=$DB-$SHORT_COMMIT

if [ ! -w $DUMP_LOC ]
then
    sudo mkdir -p $DUMP_LOC
    sudo chown atw:atw $DUMP_LOC
    sudo chmod +wx $DUMP_LOC
fi

mkdir TMP
cd TMP

pg_dump $DB > $DUMP_NAME.sql
echo $COMMIT > COMMIT
echo $PWD > REPO

tar zcf $DUMP_NAME.tar.gz COMMIT REPO $DUMP_NAME.sql
mv $DUMP_NAME.tar.gz $DUMP_LOC/.
rm $DUMP_NAME.sql COMMIT REPO

cd ..
rmdir TMP
