#! /bin/sh

if [ -z $1 ]
then
    DB=`basename $PWD`
else
    DB=$1
fi

DBSNAP_HOME=/opt/dbsnap
SHORT_COMMIT=`git rev-parse --short HEAD`
COMMIT=`git rev-parse HEAD`
DUMP_LOC=$DBSNAP_HOME/$DB
DUMP_NAME=$DB-$SHORT_COMMIT
REPO=`pwd`

if [ ! -w $DUMP_LOC ]
then
    sudo mkdir -p $DUMP_LOC
    sudo chown atw:atw $DUMP_LOC
    sudo chmod +wx $DUMP_LOC
fi

mkdir TMP
cd TMP

pg_dump $DB > $DUMP_NAME.sql
echo $COMMIT > COMMIT
echo $REPO > REPO

tar zcf $DUMP_NAME.tar.gz COMMIT REPO $DUMP_NAME.sql
mv $DUMP_NAME.tar.gz $DUMP_LOC/.
rm $DUMP_NAME.sql COMMIT REPO

cd ..
rmdir TMP
